version: '3.8'

services:
  trading-bot-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MT5_LOGIN=${MT5_LOGIN}
      - MT5_PASSWORD=${MT5_PASSWORD}
      - MT5_SERVER=${MT5_SERVER}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - REINFORCEMENT_LEARNING_ENABLED=True
    volumes:
      - ./backend:/app
      - ./src:/app/src
      - ./config:/app/config
      - ./data:/app/data
      - ./models:/app/models
      - ./journals:/app/journals
    restart: unless-stopped
    networks:
      - trading-network

  # Optional: Add a database service for production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: trading_bot
  #     POSTGRES_USER: trading_user
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - trading-network

networks:
  trading-network:
    driver: bridge

# volumes:
#   postgres_data: