symbols:
  - EURUSDm
  - GBPUSDm
  - XAUUSDm
  - GBPJPYm 
  - XAGUSDm 
  - US30
  - NAS100
  - BTCUSDm
  - ETHUSDm
  - USDJPYm

risk_parameters:
  max_drawdown: 10
  risk_per_trade: 0.02
  stop_loss: 50
  take_profit: 100
  max_trade_duration: 240

trading_settings:
  slippage: 3
  leverage: 100
  commission: 0.0005
  timezone: "Europe/London"

logging:
  log_level: INFO

rl_parameters:
  state_size: 14
  action_size: 7